#!/usr/bin/env bash
# installing engine x nginx on the first webserver

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing engine x configurations
sudo nginx -t

sudo service nginx reload

